services:
  api:
    build: ./docker/api
    container_name: "api"
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./api:/src

  client:
    container_name: client
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    # ホストPCの3000番ポートとコンテナ内の3000番ポートを接続
    ports:
      - "3000:3000" 
    volumes:
      - ./client:/src
      - /src/node_modules
    depends_on:
      - api

  nginx:
    build: ./docker/nginx
    container_name: "nginx"
    # ポートフォワードの指定（ホスト側ポート：コンテナ側ポート）
    ports:
      - 80:80
    # ボリュームを設定する（ホスト側ディレクトリ:コンテナ側ボリュームの場所）
    volumes:
      - ./api:/src
    # サービスの依存関係を指定（nginxをphpに依存させる）
    depends_on:
      - api

  mysql:
    image: mysql:8.0.37
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mysql
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
volumes:
  db-data:
  

